# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1accf9d9eee5022ec929e0b8e6199f1671901d9b2845598fd8432d26cb5ff2e8f08527c89821366f888d69a774224e53a18b2bcbfb441a55a7e0930b82913389

test:
  secret_key_base: bdc9a650ba66d8e02a6a825cd777999468819155057722fe7e4d83d8be347652ce3ac299c4a1b90390d653967c527f4688459c0bfc3318fc5e4a72af20b860db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
